remove class constructor
PrimeAcademy/object-group-bonus-calculator pull request #2
Opened 2019-01-28 22:49 UTC by LukeSchlangen

removing class constructor to reduce confusion on bonus calculator assignment

2019-01-29 17:20 UTC, Lysautumn approved these changes

2019-01-29 17:51 UTC, kdszafranski commented
The code looks fine. The larger question is are we going to wholly push off class syntax until later. And if so, when?

2019-01-29 19:53 UTC, kdszafranski requested changes
Please use another repo for this affine-only change.

2019-03-01 22:30 UTC, Lysautumn commented
Reopening PR to merge in changes - removing classes

2019-03-04 19:36 UTC, merged